"""Create AI_SCHEMA tables in Exasol and seed the FAILURE_PATTERNS vector store.

This script:
  1. Creates AI_SCHEMA.FAILURE_PATTERNS — Exasol storing nomic-embed-text embeddings.
     Each row is a historical downtime event represented as a 768-dimensional embedding
     generated by Ollama (nomic-embed-text). Stored as a comma-separated VARCHAR.
  2. Creates AI_SCHEMA.MAINTENANCE_RECOMMENDATIONS — the AI agent writes here; the dbt
     mart mart_ai_maintenance_queue reads it to close the loop.
  3. Seeds FAILURE_PATTERNS by joining downtime_events + mart_machine_health + mart_oee_daily,
     building a natural-language description per event, and embedding it via Ollama.
"""

import os
import sys

import pyexasol
import requests
from tqdm import tqdm

from ai_constants import EMBED_MODEL

# ── Connection ────────────────────────────────────────────────────────────────
EXA_DSN      = os.environ.get("EXASOL_HOST", "localhost") + ":" + os.environ.get("EXASOL_PORT", "8563")
EXA_USER     = os.environ.get("EXASOL_USER", "sys")
EXA_PASSWORD = os.environ.get("EXASOL_PASSWORD", "exasol")
OLLAMA_URL   = os.environ.get("OLLAMA_URL", "http://localhost:11434")


def log(msg):
    print(f"  {msg}", flush=True)


def create_schema_and_tables(con):
    log("Creating AI_SCHEMA ...")
    con.execute("CREATE SCHEMA IF NOT EXISTS AI_SCHEMA")

    log("Creating AI_SCHEMA.FAILURE_PATTERNS ...")
    con.execute("""
        CREATE OR REPLACE TABLE AI_SCHEMA.FAILURE_PATTERNS (
            pattern_id    INT            PRIMARY KEY,
            machine_id    INT            NOT NULL,
            machine_type  VARCHAR(50)    NOT NULL,
            event_date    DATE           NOT NULL,
            reason_code   VARCHAR(50)    NOT NULL,
            downtime_hrs  DECIMAL(8,3)   NOT NULL,
            description   VARCHAR(2000)  NOT NULL,
            embedding     VARCHAR(20000) NOT NULL
        )
    """)

    log("Creating AI_SCHEMA.MAINTENANCE_RECOMMENDATIONS ...")
    con.execute("""
        CREATE OR REPLACE TABLE AI_SCHEMA.MAINTENANCE_RECOMMENDATIONS (
            rec_id                    INT IDENTITY PRIMARY KEY,
            machine_id                INT          NOT NULL,
            machine_name              VARCHAR(100) NOT NULL,
            generated_at              TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
            anomaly_score             DECIMAL(6,3),
            root_cause                VARCHAR(1000),
            recommended_action        VARCHAR(1000),
            estimated_hours_to_failure DECIMAL(6,1),
            confidence                VARCHAR(20),
            similar_pattern_ids       VARCHAR(200)
        )
    """)
    log("Tables created.")


def fetch_historical_failures(con):
    """Retrieve all downtime events joined with sensor stats and OEE on the event day."""
    rows = con.execute("""
        SELECT
            d.machine_id,
            m.machine_type,
            CAST(DATE_TRUNC('DAY', d.started_at) AS DATE)          AS event_date,
            d.reason_code,
            h.avg_temp_c,
            h.max_temp_c,
            h.avg_vibration_mm_s,
            h.max_vibration_mm_s,
            h.avg_power_kw,
            h.max_power_kw,
            COALESCE(o.oee, 0.70)                                   AS oee,
            CAST(SECONDS_BETWEEN(d.started_at, d.ended_at) / 3600.0 AS DECIMAL(8,3)) AS downtime_hrs
        FROM IOT_RAW.DOWNTIME_EVENTS d
        JOIN ERP_PG.MACHINES m
            ON d.machine_id = m.machine_id
        LEFT JOIN MARTS.MART_MACHINE_HEALTH h
            ON d.machine_id = h.machine_id
            AND CAST(DATE_TRUNC('DAY', d.started_at) AS DATE) = h.reading_date
        LEFT JOIN MARTS.MART_OEE_DAILY o
            ON d.machine_id = o.machine_id
            AND CAST(DATE_TRUNC('DAY', d.started_at) AS DATE) = o.shift_date
        WHERE h.avg_temp_c IS NOT NULL
    """).fetchall()
    return [{k.lower(): v for k, v in r.items()} for r in rows]


def _f(val, default=0.0):
    try:
        return float(val)
    except (TypeError, ValueError):
        return default


def build_failure_description(row: dict) -> str:
    """Build a natural-language description of a historical failure event for embedding."""
    mtype  = (row["machine_type"] or "UNKNOWN").upper().strip()
    reason = (row["reason_code"] or "UNKNOWN").upper().strip()
    date_s = str(row["event_date"])[:10] if row["event_date"] else "unknown"

    return (
        f"Machine type: {mtype}\n"
        f"Failure type: {reason}\n"
        f"Date: {date_s}\n"
        f"Sensor readings on failure day:\n"
        f"  Temperature: max {_f(row['max_temp_c']):.1f}°C, average {_f(row['avg_temp_c']):.1f}°C\n"
        f"  Vibration: max {_f(row['max_vibration_mm_s']):.3f} mm/s, average {_f(row['avg_vibration_mm_s']):.3f} mm/s\n"
        f"  Power: max {_f(row['max_power_kw']):.2f} kW, average {_f(row['avg_power_kw']):.2f} kW\n"
        f"OEE: {_f(row['oee']):.1%}\n"
        f"Downtime: {_f(row['downtime_hrs']):.1f} hours"
    )


def get_embedding(text: str) -> list:
    """Call the Ollama embedding API and return a list of floats."""
    resp = requests.post(
        f"{OLLAMA_URL}/api/embed",
        json={"model": EMBED_MODEL, "input": text},
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()["embeddings"][0]


def seed_failure_patterns(con, rows):
    log(f"Generating {EMBED_MODEL} embeddings for {len(rows)} historical failure events ...")
    log("(Calls Ollama once per event — expect ~30-60 seconds)")

    batch   = []
    skipped = 0
    for pid, row in enumerate(tqdm(rows, desc="  Embedding", unit="event"), start=1):
        desc = build_failure_description(row)
        try:
            embedding = get_embedding(desc)
        except Exception as exc:
            log(f"WARNING: embedding failed for event {pid} ({exc}) — skipping.")
            skipped += 1
            continue

        embedding_str = ",".join(f"{v:.8f}" for v in embedding)
        batch.append((
            pid,
            row["machine_id"],
            (row["machine_type"] or "UNKNOWN").upper().strip(),
            row["event_date"],
            (row["reason_code"] or "UNKNOWN").upper().strip(),
            _f(row["downtime_hrs"]),
            desc,
            embedding_str,
        ))

    if not batch:
        log("No failure events embedded — skipping insert. Run 'make seed' + 'make dbt-run' first.")
        return 0

    if skipped:
        log(f"Skipped {skipped} events due to embedding errors.")

    con.import_from_iterable(batch, ("AI_SCHEMA", "FAILURE_PATTERNS"))
    log(f"Inserted {len(batch)} failure pattern embeddings into AI_SCHEMA.FAILURE_PATTERNS.")
    return len(batch)


def main():
    print("\n==> Setting up AI_SCHEMA tables ...")
    try:
        con = pyexasol.connect(dsn=EXA_DSN, user=EXA_USER, password=EXA_PASSWORD,
                               websocket_sslopt={"cert_reqs": 0}, fetch_dict=True)
    except Exception as e:
        print(f"ERROR: Cannot connect to Exasol at {EXA_DSN}: {e}")
        print("       Make sure 'make up' and 'make seed' and 'make dbt-run' have all completed.")
        sys.exit(1)

    create_schema_and_tables(con)

    print(f"\n==> Seeding FAILURE_PATTERNS ({EMBED_MODEL} via Ollama) ...")
    try:
        rows  = fetch_historical_failures(con)
        count = seed_failure_patterns(con, rows)
        print(f"    Vector store ready — {count} failure pattern embeddings stored in Exasol.")
    except Exception as e:
        print(f"  WARNING: Could not seed failure patterns: {e}")
        print("           This is normal if mart tables haven't been built yet.")
        print("           Run 'make dbt-run' first, then re-run 'make ai-setup'.")

    con.close()
    print("\n==> AI table setup complete.\n")


if __name__ == "__main__":
    main()
